bitwarden/Dockerfile
https://github.com/dani-garcia/bitwarden_rs/releases/tag/1.10.0
<blockquote><img src="https://avatars1.githubusercontent.com/u/725423?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/dani-garcia/bitwarden_rs">dani-garcia/bitwarden_rs</a></strong></div><div>Unofficial Bitwarden compatible server written in Rust - dani-garcia/bitwarden_rs</div></blockquote>
=> ⬆️ Upgrades Bitwarden RS to 1.10.0

bitwarden/Dockerfile
Upgrades Bitwarden RS to 1.11.0
=> :arrow_up: Upgrades Bitwarden RS to 1.11.0

bitwarden/Dockerfile
https://github.com/dani-garcia/bitwarden_rs/releases/tag/1.13.0
<blockquote><img src="https://avatars1.githubusercontent.com/u/725423?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/dani-garcia/bitwarden_rs">dani-garcia/bitwarden_rs</a></strong></div><div>Unofficial Bitwarden compatible server written in Rust - dani-garcia/bitwarden_rs</div></blockquote>
=> ⬆️ Upgrades BitwardenRS to 1.13.0

bitwarden/Dockerfile
Upgrades BitwardenRS to 1.14
https://github.com/dani-garcia/bitwarden_rs/releases/
> (Describe the changes and rationale behind them)
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
<blockquote><img src="https://avatars1.githubusercontent.com/u/725423?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/dani-garcia/bitwarden_rs">dani-garcia/bitwarden_rs</a></strong></div><div>Unofficial Bitwarden compatible server written in Rust - dani-garcia/bitwarden_rs</div></blockquote>
=> :arrow_up: Upgrades BitwardenRS to 1.14

bitwarden/Dockerfile
Upgrades BitwardenRS to 1.14.1
> (Describe the changes and rationale behind them)
https://github.com/dani-garcia/bitwarden_rs/releases
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
<blockquote><img src="https://avatars1.githubusercontent.com/u/725423?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/dani-garcia/bitwarden_rs">dani-garcia/bitwarden_rs</a></strong></div><div>Unofficial Bitwarden compatible server written in Rust - dani-garcia/bitwarden_rs</div></blockquote>
=> :arrow_up: Upgrades Bitwarden RS to 1.14.1

LICENSE.md, README.md, bitwarden/.README.j2, bitwarden/DOCS.md
=> Happy New Year

bitwarden/Dockerfile
:arrow_up: Upgrades nginx to 1.14.2-2+deb10u3
=> :arrow_up: Upgrades nginx to 1.14.2-2+deb10u3

bitwarden/Dockerfile
Upgrades Bitwarden RS to 1.18.0
<https://github.com/dani-garcia/bitwarden_rs/releases/tag/1.18.0>
=> :arrow_up: Upgrades Bitwarden RS to 1.18.0

bitwarden/Dockerfile, bitwarden/build.json
https://github.com/hassio-addons/addon-debian-base/releases/tag/v4.0.0
=> Upgrade add-on base image to 4.0.0

bitwarden/Dockerfile
Adds new and missing dependencies for Postgre, MariaDB/MySQL and SQLite.
=> Add missing database dependencies

bitwarden/DOCS.md
Small tweaks to the documentation.
=> Documentation tweaks

bitwarden/Dockerfile
=> :arrow_up: Upgrades libpq5 to 11.10-0+deb10u1

bitwarden/Dockerfile, bitwarden/build.json
=> Upgrade add-on base image to 4.1.2

bitwarden/Dockerfile
Release notes:
<https://github.com/dani-garcia/bitwarden_rs/releases/tag/1.19.0>
=> :arrow_up: Upgrades BitwardenRS to 1.19.0

bitwarden/Dockerfile
Upgrades libpq5 to 11.11-0+deb10u1
=> ⬆️ Upgrades libpq5 to 11.11-0+deb10u1

bitwarden/Dockerfile
https://github.com/dani-garcia/bitwarden_rs/releases/tag/1.20.0
=> ⬆️ Upgrades BitwardenRS to 1.20.0

bitwarden/Dockerfile, bitwarden/build.json
Upgrades add-on base image to v4.1.3
=> ⬆️ Upgrades add-on base image to v4.1.3

bitwarden/Dockerfile, bitwarden/build.json
Upgrades add-on base image to v4.1.4
=> ⬆️ Upgrades add-on base image to v4.1.4

bitwarden/Dockerfile, bitwarden/build.json
Upgrades add-on base image to v4.2.0
=> Upgrades add-on base image to v4.2.0

bitwarden/translations/en.yaml
Add translation support to the add-on configuration.
=> Add add-on translation support

bitwarden/.README.j2, bitwarden/DOCS.md, bitwarden/Dockerfile, bitwarden/config.json, bitwarden/rootfs/etc/services.d/bitwarden/run, bitwarden/translations/en.yaml
Upgrades the add-on to Vaultwarden 1.21.0
Bitwarden RS has renamed: Vaultwarden.
Most changes here are there to reflect that as well.
Upstream release notes: <https://github.com/dani-garcia/vaultwarden/releases/tag/1.21.0>
=> ⬆️ Upgrades Vaultwarden to 1.21.0

bitwarden/Dockerfile, bitwarden/build.json
Upgrades add-on base image to v4.2.1
=> ⬆️ Upgrades add-on base image to v4.2.1

bitwarden/Dockerfile
Upgrades add-on base image to v4.2.2
=> ⬆️ Upgrades add-on base image to v4.2.2

bitwarden/Dockerfile
- https://github.com/dani-garcia/vaultwarden/releases/tag/1.22.0
- https://github.com/dani-garcia/vaultwarden/releases/tag/1.22.1
=> ⬆️ Upgrades Vaultwarden to 1.22.1

bitwarden/Dockerfile, bitwarden/build.json
Upgrades add-on base image to v4.2.3
=> ⬆️ Upgrades add-on base image to v4.2.3

bitwarden/Dockerfile
Upgrades Vaultwarden to 1.22.2
=> ⬆️ Upgrades Vaultwarden to 1.22.2

README.md, bitwarden/.README.j2, bitwarden/DOCS.md, bitwarden/config.json
Step 2 in getting used to the new name process, put Vaultwarden in front.
=> ✏️ Swap Bitwarden & Vaultwarden

bitwarden/Dockerfile, bitwarden/build.json
Upgrades the add-on base image to v5.0.0, which is based on Debian 11: Bullseye
=> ⬆️ Upgrades add-on base image to v5.0.0

bitwarden/config.json
=> 🚑 Start add-on as service to prevent timezone issues

bitwarden/Dockerfile
Upgrades libpq5 to 13.4-0+deb11u1
=> ⬆️ Upgrades libpq5 to 13.4-0+deb11u1

bitwarden/Dockerfile
Upgrades libmariadb-dev-compat to 1:10.5.12-0+deb11u1
=> ⬆️ Upgrades libmariadb-dev-compat to 1:10.5.12-0+deb11u1

bitwarden/Dockerfile, bitwarden/build.yaml
Upgrades add-on base image to 5.2.0
=> ⬆️ Upgrades add-on base image to 5.2.0

bitwarden/Dockerfile
https://github.com/dani-garcia/vaultwarden/releases/tag/1.23.0
=> ⬆️ Upgrades Vaultwarden to 1.23.0

bitwarden/Dockerfile, bitwarden/build.yaml
Upgrades add-on base image to 5.2.2
=> ⬆️ Upgrades add-on base image to 5.2.2

bitwarden/Dockerfile
Upgrades libpq5 to 13.5-0+deb11u1
=> ⬆️ Upgrades libpq5 to 13.5-0+deb11u1

bitwarden/Dockerfile
https://github.com/dani-garcia/vaultwarden/releases/tag/1.23.1
=> ⬆️ Upgrades Vaultwarden to 1.23.1

LICENSE.md, README.md, bitwarden/.README.j2, bitwarden/DOCS.md
=> :fireworks: Updates maintenance/license year to 2022

bitwarden/Dockerfile, bitwarden/build.yaml
Upgrades add-on base image to 5.2.3
=> ⬆️ Upgrades add-on base image to 5.2.3

bitwarden/Dockerfile
https://github.com/dani-garcia/vaultwarden/releases/tag/1.24.0
=> ⬆️ Upgrades Vaultwarden to 1.24.0

bitwarden/Dockerfile, bitwarden/build.yaml
Upgrades add-on base image to 5.3.0
=> ⬆️ Upgrades add-on base image to 5.3.0

.github/workflows/deploy.yaml, bitwarden/build.yaml, bitwarden/config.yaml
Sign add-on with Codenotary Community Attestation Service (CAS)
=> :lock: Sign add-on with Codenotary Community Attestation Service (CAS)

bitwarden/DOCS.md
Making it easier to find the add-on.
=> :books: Add My buttons to documentation

bitwarden/Dockerfile
Upgrades libmariadb-dev-compat to 1:10.5.15-0+deb11u1
=> ⬆️ Upgrades libmariadb-dev-compat to 1:10.5.15-0+deb11u1

bitwarden/DOCS.md
Update the URL for the My Home Assistant add-on link, doing a one-shot with the right repository as well.
=> :books: Use new My Home Assistant link format

bitwarden/Dockerfile
https://github.com/dani-garcia/vaultwarden/releases/tag/1.25.0
=> ⬆️ Upgrades Vaultwarden to 1.25.0

bitwarden/Dockerfile, bitwarden/build.yaml, bitwarden/rootfs/etc/cont-init.d/nginx.sh, bitwarden/rootfs/etc/services.d/bitwarden/finish, bitwarden/rootfs/etc/services.d/bitwarden/run, bitwarden/rootfs/etc/services.d/nginx/finish, bitwarden/rootfs/etc/services.d/nginx/run
Upgrades add-on base image to 6.0.0
=> ⬆️ Upgrades add-on base image to 6.0.0

bitwarden/Dockerfile, bitwarden/build.yaml
Upgrades add-on base image to 6.1.0
=> ⬆️ Upgrades add-on base image to 6.1.0

bitwarden/Dockerfile
https://github.com/dani-garcia/vaultwarden/releases/tag/1.25.2
=> ⬆️ Upgrades Vaultwarden to 1.25.2

bitwarden/Dockerfile, bitwarden/build.yaml
Upgrades add-on base image to 6.1.1
=> ⬆️ Upgrades add-on base image to 6.1.1

bitwarden/Dockerfile, bitwarden/build.yaml
Upgrades the hassio debian base image to the latest Version 6.1.2
https://github.com/hassio-addons/addon-debian-base/releases/tag/v6.1.2
=> ⬆️ Upgrades add-on base image to 6.1.2

bitwarden/Dockerfile, bitwarden/build.yaml
Upgrades the hassio debian base image to the latest Version 6.1.3
https://github.com/hassio-addons/addon-debian-base/releases/tag/v6.1.3
=> ⬆️ Upgrades add-on base image to 6.1.3

bitwarden/Dockerfile, bitwarden/build.yaml
=> ⬆️ Upgrades add-on base image to 6.2.0

bitwarden/DOCS.md
Changed the step where a referral is made to the step where the token is obtained
> (Describe the changes and rationale behind them)
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
=> 📚 Fix step reference in installation steps

LICENSE.md, README.md, bitwarden/.README.j2, bitwarden/DOCS.md
=> :fireworks: Updates maintenance/license year to 2023

bitwarden/Dockerfile, bitwarden/build.yaml
=> ⬆️ Upgrades add-on base image to 6.2.3

LICENSE.md, README.md, bitwarden/.README.j2, bitwarden/DOCS.md
=> :fireworks: Updates maintenance/license year to 2024
